apiVersion: v1
kind: Pod
metadata:
  name: ansible-pod
spec:
  containers:
  - name: ansible-container
    image: ubuntu:20.04
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
