# nginx-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: ubuntu:20.04
    command: ["/bin/bash", "-c", "--"]
    args: ["apt update && apt install -y nginx openssh-server && service ssh start && service nginx start && while true; do sleep 30; done;"]
